openapi: 3.0.0
info:
  title: Keycap Archivist api v2
  description: Keycap archivist Api
  version: 0.0.1
servers:
  - url: https://app.keycap-archivist.com/api/v2/
paths:
  /img/{id}:
    parameters:
      - name: id
        description: id of the keycap
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: getImg
      responses:
        '200':
          description: resized/proxied image of the keycap
          content:
            image/jpg:
              schema:
                type: string
                format: binary
        '404':
          description: Keycap not found
        '500':
          description: Internal Server Error
  /wishlist-settings:
    get:
      operationId: getWishlistSettings
      responses:
        '200':
          description: available settings for the wishlist generation
        '500':
          description: Internal Server Error
  /wishlist:
    post:
      operationId: postWishlist
      requestBody:
        description: The wishlist to be generated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wishlist'
      responses:
        '200':
          description: image of the generated wishlist
          content:
            image/jpg:
              schema:
                type: string
                format: binary
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /table:
    post:
      operationId: postWishListTable
      requestBody:
        description: The wishlist object
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
      responses:
        '200':
          description: Markdown markup
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
  /submission:
    post:
      operationId: submitCap
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - maker
                - sculpt
                - colorway
              properties:
                maker:
                  type: string
                sculpt:
                  type: string
                colorway:
                  type: string
            encoding:
              profileImage:
                contentType: image/png, image/jpeg
      responses:
        '200':
          description: Confirmation of submission
        '500':
          description: Internal Server Error
  /submission/{id}:
    parameters:
      - name: id
        description: id of the submission
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: getSubmissionCap
      responses:
        '200':
          description: Submission image
          content:
            image/jpg:
              schema:
                type: string
                format: binary
        '404':
          description: Submission not found
        '500':
          description: Internal Server Error
  /submitName:
    post:
      operationId: submitName
      requestBody:
        description: Submission name object
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - name
              properties:
                id:
                  type: string
                name:
                  type: string
      responses:
        '200':
          description: Confirmation of submission
        '500':
          description: Internal Server Error
  /fkunav:
    get:
      operationId: fkunav
      responses:
        '508':
          description: What did you expect
          content:
            text/plain; charset=utf-8:
              schema:
                type: string

components:
  schemas:
    wishlist:
      type: object
      required:
        - caps
      properties:
        caps:
          type: array
          items:
            type: object
            required:
              - id
            properties:
              id:
                type: string
              legend:
                type: string
                maxLength: 50
              legendColor:
                type: string
              isPriority:
                type: boolean
        settings:
          type: object
          properties:
            capsPerLine:
              type: integer
            priority:
              $ref: '#/components/schemas/textCustomization'
            legends:
              $ref: '#/components/schemas/textCustomization'
            title:
              $ref: '#/components/schemas/textOption'
            extraText:
              $ref: '#/components/schemas/textOption'
            background:
              type: object
              properties:
                color:
                  type: string
            social:
              type: object
              properties:
                reddit:
                  type: string
                discord:
                  type: string
    textCustomization:
      type: object
      properties:
        color:
          type: string
        font:
          type: string
    textOption:
      allOf:
        - $ref: '#/components/schemas/textCustomization'
        - type: object
          properties:
            text:
              type: string
              maxLength: 50
