schema {
  query: Query
}

type Query {
  dbVersion: String

  allArtists: [Artist]
  artist(id: String): Artist

  allSculpts(artistId: String): [Sculpt]
  sculpt(id: String): Sculpt

  allColorways(sculptId: String): [Colorway]
  colorway(id: String): Colorway
}

type Artist {
  id: String
  name: String
  instagram: String
  website: String
  sculpts: [Sculpt]!
}

type Sculpt {
  id: String
  name: String
  colorways: [Colorway]
}

type Colorway {
  id: String
  name: String
  img: String
}
