name: Image Build

on:
  repository_dispatch:
    types:
      - base_image_build
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          dockerfile: Dockerfile
          name: keycap-archivist/app/api
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest"
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SRV_HOST }}
          username: ${{ secrets.SRV_USERNAME }}
          password: ${{ secrets.SRV_PASSWORD }}
          port: ${{ secrets.SRV_PORT }}
          script: |
            cd artisans
            docker-compose pull
            docker-compose down
            docker-compose up -d
            docker rmi -f $(docker images -f "dangling=true" -q) || true
