name: Ui pipeline

on:
  pull_request:
    paths:
      - .github/workflows/ui.yaml
      - ui/**
  push:
    paths:
      - .github/workflows/ui.yaml
      - ui/**
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ui/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('ui/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: install
        run: |
          cd ui
          yarn
      - name: lint
        run: |
          cd ui
          yarn lint
      - name: build
        run: |
          cd ui
          yarn build
